# project setup 
spring:
  application:
    name: livi-coding-challenge
  profiles:
    active:
    - local

  session:
    store-type: none
        
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT+8

server:
  port: 8089
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    excluded-user-agents: 
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json            


# Set whether to append stack trace to the error message in generic error response.
# see com.livi.coding.challenge.demo.controlleradvice.DefaultExceptionAdvice
# Useful for DEV env     
livi:
  error-show-stack-trace: false
  max-employee-no: 99999
  min-employee-no: 1
  max-operate-year-no: 99999
  min-operate-year-no: 0
 




